const DASHBOARD_HOME = "/dashboard";
const DASHBOARD_LOGIN = "/";
const CUSTOMER = "/dashboard/customer";

const PRIVATE_ROUTES = [DASHBOARD_HOME, CUSTOMER];
const AUTH_ROUTES = [DASHBOARD_LOGIN];

export { PRIVATE_ROUTES, AUTH_ROUTES, DASHBOARD_HOME, DASHBOARD_LOGIN };
